# Generated by Django 3.0.4 on 2020-09-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
