# Generated by Django 3.0.4 on 2020-09-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='\\media\\default.jpg', upload_to='profile_pics'),
        ),
    ]
