# Generated by Django 3.0.4 on 2020-09-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_auto_20200923_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about',
            field=models.CharField(default='', max_length=30),
        ),
    ]
