# Generated by Django 3.0.4 on 2020-09-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_post_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cast',
            field=models.CharField(default='', max_length=100),
        ),
    ]
