# Generated by Django 3.0.4 on 2020-09-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_post_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='director',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(default='', max_length=100),
        ),
    ]
