# Generated by Django 3.0.4 on 2020-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_post_premiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
