# Generated by Django 3.0.4 on 2020-10-20 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_post_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App1.Post')),
                ('day', models.CharField(default='', max_length=15)),
                ('date1', models.DateTimeField(default=django.utils.timezone.now)),
                ('date2', models.DateTimeField(default=django.utils.timezone.now)),
                ('date3', models.DateTimeField(default=django.utils.timezone.now)),
                ('date4', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
