# Generated by Django 3.0.4 on 2020-11-12 13:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0014_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now_add=True), blank=True, null=True, size=None),
        ),
    ]
