# Generated by Django 3.0.4 on 2020-11-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_post_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dates',
        ),
    ]
