# Generated by Django 3.0.4 on 2020-10-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
